apiVersion: v1
kind: Pod
metadata:
  name: hello-go-resources
spec:
  containers:
    - image: cybersamx/hello-go:latest
      name: hello-go
      ports:
        - containerPort: 8080
      # Detailed resources configuration.
      resources:
        requests:
          cpu: "500m"
          memory: "64Mi"
        limits:
          cpu: "1000m"
          memory: "128Mi"
