apiVersion: v1
kind: Pod
metadata:
  name: hello-go-ports
spec:
  containers:
    - image: cybersamx/hello-go:latest
      name: hello-go
      # Detailed ports configuration.
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
