apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-go
  namespace: default
  labels:
    app: env-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: env-go
  template:
    metadata:
      labels:
        app: env-go
    spec:
      containers:
        - name: env-go
          image: cybersamx/env-go:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ADDRESS
              value: ':8080'
            - name: IS_WORKER
              value: 'false'
            - name: IS_MASTER
              value: 'false'
          imagePullPolicy: Always
      restartPolicy: Always
