kind: Service
apiVersion: v1
metadata:
  name: env-go-svc
  namespace: default
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: env-go
  type: LoadBalancer
