# Default values for env-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

namespace: default

image:
  repository: cybersamx/env-go
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  - name: ADDRESS
    value: ':8080'
  - name: IS_WORKER
    value: 'true'
  - name: ABITRARY
    value: 'blah'

workerMode:
  masterEnv:
    - name: IS_MASTER
      value: 'true'
  slaveEnv:
    - name: IS_MASTER
      value: 'false'
