apiVersion: v1
kind: Service
metadata:
  name: {{ include "env-go.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "env-go.labels" . | nindent 4 }}
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    {{- include "env-go.selectorLabels" . | nindent 4 }}
