apiVersion: v1
kind: Pod
metadata:
  name: hello-go
  labels:
    app: hello
    version: 1.0.0
spec:
  containers:
    - image: gcr.io/cybersamx-public/hello-go:latest
      name: hello-go
      ports:
        - containerPort: 8080
