apiVersion: v1
kind: Service
metadata:
  name: hello-svc-loadbalancer
spec:
  ports:
    - port: 8080
  type: LoadBalancer
  # Use the selector to associate this service to a pod.
  selector:
    app: hello
