apiVersion: v1
kind: Service
metadata:
  name: hello-svc-headless
spec:
  ports:
    - port: 8080
  type: ClusterIP
  # Set clusterIP to none to denote a headless.
  clusterIP: None
  # Use the selector to associate this service to a pod.
  selector:
    app: hello
